# Generated by Django 3.0.8 on 2020-08-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_auto_20200802_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='Default Value'),
            preserve_default=False,
        ),
    ]
