# Generated by Django 3.1 on 2020-08-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorited_books', to='books.User'),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
